#!/bin/bash

apt update -y
apt install -y systemd

mkdir -p /path/to/folder1 /path/to/folder2

echo "#!/bin/bash
FOLDER1=\"/path/to/folder1\"
FOLDER2=\"/path/to/folder2\"

while true; do
    for file in \"\$FOLDER1\"/*; do
        if [ -f \"\$file\" ]; then
            mv \"\$file\" \"\$FOLDER2\"
        fi
    done
    sleep 1
done" > /path/to/move-script.sh

chmod +x /path/to/move-script.sh

echo "[Unit]
Description=Переміщення файлів з Folder1 до Folder2
After=network.target

[Service]
ExecStart=/path/to/move-script.sh
Restart=always
User=ubuntu
Group=ubuntu

[Install]
WantedBy=multi-user.target" > /etc/systemd/system/movefiles.service

systemctl daemon-reload
systemctl enable movefiles.service
systemctl start movefiles.service